### ISSUE TITLE
Move every example GraphQL project to a Micronaut Guide

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-graphql#241]
@timyates I would like you to move every example project to a Micronaut Guide. 

Those examples don't participate in the documentation and they would be more discoverable by users in guides.

#### chat
- [ ] Example deletion PR
- [ ] Guide PR 

####  jwt-security
- [ ] Example deletion PR
- [ ] Guide PR 

#### todo-java-tools
- [ ] Example deletion PR
- [ ] Guide PR 

#### todo
- [x] Example deletion PR
- [x] Guide PR 

#### todo-spqr
- [ ] Example deletion PR
- [ ] Guide PR
